name: Linky
description: Sync Energy dashboards with Linky smart meters
version: 0.1.0
slug: linky
init: false
url: https://github.com/bokub/ha-linky
image: ghcr.io/bokub/ha-linky-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
options:
  consumption PRM: ''
  consumption token: ''
  consumption action: sync
schema:
  consumption PRM: str?
  consumption token: str?
  consumption action: list(sync|reset)
