name: Linky
description: Sync Energy dashboards with your Linky smart meter
version: 1.3.1
slug: linky
init: false
url: https://github.com/bokub/ha-linky
image: ghcr.io/bokub/ha-linky-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
options:
  meters:
    - prm: ''
      token: ''
      name: 'Linky consumption'
      action: 'sync'
      production: false
    - prm: ''
      token: ''
      name: 'Linky production'
      action: 'sync'
      production: true
schema:
  meters:
    - prm: str?
      token: str?
      name: str?
      action: list(sync|reset)
      production: bool?
